//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Bugle
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdsSet
    {
        public int ID { get; set; }
        public int IdOrg { get; set; }
        public int IdGaz { get; set; }
        public string Num { get; set; }
        public string Obem { get; set; }
    
        public virtual GazSet GazSet { get; set; }
        public virtual OrgSet OrgSet { get; set; }
    }
}
